### ISSUE TITLE
Minimized cmd.EXE

### ISSUE THREAD

**Issue by Guceri** [jwijffels/taskscheduleR#52]
Is there a way to default the cmd window to stay minimized while the process runs?  I have a script that takes some time and is run often and the pop up is frequent.  Is this something that is possible within the package?

**Comment by jwijffels** [comment]
Same question as #32

**Comment by Guceri** [comment]
Thank you. That answered the question and seems to have worked.  I do seem
to be running into a new road block in which the packages on the script
that is scheduled to run do not load. There is an error message saying the
package can not be found. I have tried reinstalling all the packages (and
even their dependencies) using an admin instance of Rstudio.

When taskscheduler is not run as admin, the script fires on schedule
normally (but obviously the cmd window keeps popping up).  I think there is
one more step here that I am missing to link the packages so they are
seen.  Any suggestions?

**Comment by Guceri** [comment]
I was able to solve it  using .libPaths() I was able to find that there
were two library paths. I just copied the packages from one to the other
and that seems to solve the problem.  I don't quite understand though why
the package directory is changed when using "SYSTEM" as your log in with
taskscheduler.

**Comment by jwijffels** [comment]
Because you now run your R script as the system user instead of your own user. The system user does not have the library folder of your user available. The example R script in the package (https://github.com/bnosac/taskscheduleR/blob/master/inst/extdata/helloworld.R) which is used in all the examples given in the R package shows the libPaths and also shows the environment variables which will also be different of course than if you run it as your user instead of the system user. 
Either way, I think you found a reasonable solution to your problem. Closing.
